// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKhXs508VGBjV4fDM8MY9zx2f1A4ktEuY',
    appId: '1:966658683880:web:8f80bab3c18c7587816a5d',
    messagingSenderId: '966658683880',
    projectId: 'lession-labs',
    authDomain: 'lession-labs.firebaseapp.com',
    storageBucket: 'lession-labs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMurjahFJHXy0YnnwsNMP4XzW5ls5E0TQ',
    appId: '1:966658683880:android:a64e9b74d16f213a816a5d',
    messagingSenderId: '966658683880',
    projectId: 'lession-labs',
    storageBucket: 'lession-labs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdJPOnQGgUPoDFYqtPbty5q4THatP_lxE',
    appId: '1:966658683880:ios:ff7461dc4343c0e4816a5d',
    messagingSenderId: '966658683880',
    projectId: 'lession-labs',
    storageBucket: 'lession-labs.appspot.com',
    iosBundleId: 'com.example.lessionlab',
  );
}
